name: 'Build Python Package'
description: 'Sets up Python, builds package, and validates it'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.8'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip and setuptools
      shell: bash
      run: python -m pip install --upgrade pip setuptools

    - name: Install dependencies
      shell: bash
      run: pip install twine wheel
      
    - name: Setup deployment
      shell: bash
      run: python setup.py sdist bdist_wheel
    
    - name: Validate deployment
      shell: bash
      run: twine check dist/*