name: "Test"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install -e .[test]

      - name: Run linter
        run: pre-commit run --all-files

      - name: Run tests
        run: python -m pytest --cov --cov-config=.coveragerc